The following function:
RoaringBitmap/CRoaring pull request #386
Opened 2022-09-03 14:22 UTC by pjulien

The following function:

```c++
    /**
     * Returns true if the bitmap is empty (cardinality is zero).
     */
    bool isEmpty() const {
        return std::all_of(roarings.cbegin(), roarings.cend(),
                           [](const std::pair<const uint32_t, Roaring>
&map_entry) {
                               return map_entry.second.isEmpty();
                           });
    }
```

creates temporaries via implicit conversion.  This is because
the map entries from this location are of type:

```c++
const std::pair<const uint32_t, const Roaring>

```

which cannot be bound to:

```c++
const std::pair<const uint32_t, Roaring>
```

As it would make the Roaring component of the pair mutable.

Since this is not allowed the compiler looks for a compatible conversion
using overloading rules which leads it to ``Roaring``'s copy constructor.

In other words, for every call to that lambda a temporary copy of the
roaring bitmap is fully constructed, used and then immediately
discarded.

This can be fixed by using the right type for the argument or by using
``auto`` and letting the compiler determine the type by itself.

I prefer the latter but chose the format to retain C++11 compatibility.

2022-09-03 20:13 UTC, lemire commented
Looks good, but I would like one other person to review this.

2022-09-03 21:37 UTC, Dr-Emann requested changes
Funnily enough, making this change does the opposite of what you want, the code currently doesn't call any copy constructors, but changing it in this way _does_. The [type](https://en.cppreference.com/w/cpp/container/map/begin) of `std::map`'s `cbegin`/`cend` types are `std::map<..>::const_iterator`. `const_iterator` is defined as `LegacyBidirectionalIterator to const value_type`, and `value_type` is defined as `std::pair<const Key, T>` (see [map docs](https://en.cppreference.com/w/cpp/container/map)). Replacing our types, the iterators are over `const std::pair<const uint32_t, Roaring>`, **not** `const std::pair<const uint32_t, const Roaring>`.

This can be confirmed by placing a breakpoint/printf in the copy constructor with code like:

```c++
int main() {
    Roaring64Map r;
    r.add(0xFFFFFFFFULL);
    r.add(0xFFFFFFFFFFULL);
    bool x = r.isEmpty();
    std::cout << x << "\n";
}
```

Without this change, the output is:
```
0
```

With this change, the output is:
```
COPY CONSTRUCTOR
0
```

2022-09-05 15:03 UTC, lemire commented
@pjulien Do you agree with @Dr-Emann ? If so, I will close the issue.

2022-09-06 14:47 UTC, pjulien commented
I have the stack traces that show copies being performed here in real production code.  Personally I would suggest using ``auto`` instead to remove any possibility of a copy but I'm not sure what the baseline C++ standard for this project is.  Using ``auto`` for lambda arguments was added in C++14.

2022-09-06 14:57 UTC, madscientist commented
@pjulien please provide a minimal complete repro case for this then we can examine it.  A backtrace doesn't really help.  It shouldn't be too difficult to create an example that elicits the behavior you're seeing without publishing any proprietary code.

2022-09-06 16:22 UTC, pjulien commented
It looks like it's fixed if I update to latest, I believe I misread, the copy is coming from the invocation of ``std::pair`` in the stacktrace

2022-09-06 16:22 UTC, closed without merging